In [1]:
import pandas as pd
import sqlite3
import os

Data loading

In [ ]:
base_path = "f:/"  
years = ["2023", "2024"]

In [3]:
# Connect to SQL

conn = sqlite3.connect("LOT_benchmark_1.db")

In [6]:
# Import all CSV

for year in years:
    year_path = os.path.join(base_path, year)
    files = [f for f in os.listdir(year_path) if f.endswith(".csv")]

    for file in files:
        table_name = file.replace(".csv", "")
        file_path = os.path.join(year_path, file)

        df = pd.read_csv(file_path)
        df.to_sql(table_name, conn, if_exists="replace", index=False)


# Check tables in database

tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("\nDatabase Tables:")
print(tables)

Database Tables:
          name
0   2023_LOT_A
1   2023_LOT_B
2   2023_LOT_C
3   2023_LOT_D
4   2023_LOT_E
5   2023_LOT_F
6   2023_LOT_G
7   2023_LOT_H
8   2023_LOT_I
9   2023_LOT_J
10  2024_LOT_A
11  2024_LOT_B
12  2024_LOT_C
13  2024_LOT_D
14  2024_LOT_E
15  2024_LOT_F
16  2024_LOT_G
17  2024_LOT_H
18  2024_LOT_I
19  2024_LOT_J

Data processing

In [100]:
# Check NaN value

tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
table_names = tables['name'].tolist()
print(table_names)


for table in table_names:
    print(f"\n Missing values in {table} ...")
    df = pd.read_sql(f"SELECT * FROM '{table}'", conn)
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if missing.empty:
        print("No missing values")
    else:
        print(missing)

['2023_LOT_A', '2023_LOT_B', '2023_LOT_C', '2023_LOT_D', '2023_LOT_E', '2023_LOT_F', '2023_LOT_G', '2023_LOT_H', '2023_LOT_I', '2023_LOT_J', '2024_LOT_A', '2024_LOT_B', '2024_LOT_C', '2024_LOT_D', '2024_LOT_E', '2024_LOT_F', '2024_LOT_G', '2024_LOT_H', '2024_LOT_I', '2024_LOT_J']

 Missing values in 2023_LOT_A ...
No missing values

 Missing values in 2023_LOT_B ...
No missing values

 Missing values in 2023_LOT_C ...
No missing values

 Missing values in 2023_LOT_D ...
Country     7724
Geo_code    7724
dtype: int64

 Missing values in 2023_LOT_E ...
Profile_label_-_category        4329
Profile_label_-_sub-category    4329
Code                            4329
dtype: int64

 Missing values in 2023_LOT_F ...
No missing values

 Missing values in 2023_LOT_G ...
No missing values

 Missing values in 2023_LOT_H ...
No missing values

 Missing values in 2023_LOT_I ...
No missing values

 Missing values in 2023_LOT_J ...
Eng._Rate       90
Lien_image     434
Lien_vidéo    1385
dtype: int64

 Missing values in 2024_LOT_A ...
No missing values

 Missing values in 2024_LOT_B ...
No missing values

 Missing values in 2024_LOT_C ...
No missing values

 Missing values in 2024_LOT_D ...
Country     10540
Geo_code    10541
dtype: int64

 Missing values in 2024_LOT_E ...
Profile_label_-_category        1484
Profile_label_-_sub-category    1484
Code                            1484
dtype: int64

 Missing values in 2024_LOT_F ...
No missing values

 Missing values in 2024_LOT_G ...
No missing values

 Missing values in 2024_LOT_H ...
No missing values

 Missing values in 2024_LOT_I ...
No missing values

 Missing values in 2024_LOT_J ...
Eng._Rate     177
Lien_image    339
Lien_vidéo    203
dtype: int64

In [7]:
# Modify columns' names

for table in tables["name"]:
    df = pd.read_sql(f"SELECT * FROM '{table}'", conn)
    df.columns = [col.replace(" ", "_") for col in df.columns]
    df.to_sql(table, conn, if_exists="replace", index=False)

Analysis

1. Brand Ranking 2023 vs 2024 by  
EMV /Impressions /Engagements /Post /Profiles

In [44]:
# Calculate brand ranking by KPIs and add market

def brand_ranking(year):
    query = f"""
    SELECT
        I.Brand_name AS brand_name,
        D.Geo_code AS market,
        SUM(J.Emv) AS total_emv,
        SUM(J.Impressions) AS total_impressions,
        SUM(J.Likes + J.Comments + J.Shares) AS total_engagements,
        COUNT(DISTINCT J.Post_id) AS total_posts,
        COUNT(DISTINCT C.Ally_id) AS total_profiles
    FROM "{year}_LOT_J" AS J
    LEFT JOIN "{year}_LOT_H" AS H ON J.Post_id = H.Post_id
    LEFT JOIN "{year}_LOT_I" AS I ON H.Brand_id = I.Brand_id
    LEFT JOIN "{year}_LOT_A" AS A ON H.Post_id = A.Post_id
    LEFT JOIN "{year}_LOT_C" AS C ON A.Account_id = C.Account_id
    LEFT JOIN (
        SELECT DISTINCT Ally_id, Geo_code
        FROM "{year}_LOT_D"
    ) AS D ON C.Ally_id = D.Ally_id
    GROUP BY I.Brand_name, D.Geo_code
    ORDER BY total_emv DESC;
    """
    df = pd.read_sql(query, conn)

    df["rank_emv"] = df["total_emv"].rank(ascending=False, method="dense")
    df["rank_impressions"] = df["total_impressions"].rank(ascending=False, method="dense")
    df["rank_engagements"] = df["total_engagements"].rank(ascending=False, method="dense")
    df["rank_posts"] = df["total_posts"].rank(ascending=False, method="dense")
    df["rank_profiles"] = df["total_profiles"].rank(ascending=False, method="dense")

    df["year"] = year
    return df

In [45]:
rank_2023 = brand_ranking("2023")
rank_2024 = brand_ranking("2024")

brand_compare = rank_2023.merge(
    rank_2024,
    on=["brand_name", "market"],   
    suffixes=("_2023", "_2024"),
    how="outer"  
)

In [46]:
print(brand_compare)

           brand_name market  total_emv_2023  total_impressions_2023  \
0                None   None      26348260.0            1.756907e+09
1          YSL Beauty   None      17489169.0            1.166063e+09
2       MAC Cosmetics   None      17314033.0            1.154402e+09
3             Lancome   None      13885839.0            9.258288e+08
4       Armani Beauty   None      11755431.0            7.837454e+08
...               ...    ...             ...                     ...
3802     Gucci Beauty     CV             NaN                     NaN
3803           La Mer     CV             NaN                     NaN
3804  Tom Ford Beauty     CV             NaN                     NaN
3805           Byredo     PS             NaN                     NaN
3806          Benefit     ET             NaN                     NaN

      total_engagements_2023  total_posts_2023  total_profiles_2023  \
0                 98552230.0           12371.0                  0.0
1                 36210719.0            4204.0               1549.0
2                 49218202.0            4945.0               1433.0
3                 23489841.0            3768.0               1309.0
4                 15931573.0            1819.0                841.0
...                      ...               ...                  ...
3802                     NaN               NaN                  NaN
3803                     NaN               NaN                  NaN
3804                     NaN               NaN                  NaN
3805                     NaN               NaN                  NaN
3806                     NaN               NaN                  NaN

      rank_emv_2023  rank_impressions_2023  rank_engagements_2023  ...  \
0               1.0                    1.0                    1.0  ...
1               2.0                    2.0                    7.0  ...
2               3.0                    3.0                    2.0  ...
3               4.0                    4.0                   15.0  ...
4               5.0                    5.0                   20.0  ...
...             ...                    ...                    ...  ...
3802            NaN                    NaN                    NaN  ...
3803            NaN                    NaN                    NaN  ...
3804            NaN                    NaN                    NaN  ...
3805            NaN                    NaN                    NaN  ...
3806            NaN                    NaN                    NaN  ...

      total_impressions_2024  total_engagements_2024 total_posts_2024  \
0               1.410869e+09              70866217.0          13110.0
1               2.554223e+09             115055200.0          12871.0
2               1.580363e+09              95335298.0          10788.0
3               1.930390e+09              56035403.0           7733.0
4               2.528929e+09              73155372.0           7359.0
...                      ...                     ...              ...
3802            1.990000e+02                    29.0              1.0
3803            1.990000e+02                    29.0              1.0
3804            1.990000e+02                    29.0              1.0
3805            1.310000e+02                    12.0              1.0
3806            0.000000e+00                     0.0              1.0

      total_profiles_2024  rank_emv_2024  rank_impressions_2024  \
0                     0.0            6.0                    6.0
1                  3223.0            1.0                    1.0
2                  2466.0            4.0                    4.0
3                  2134.0            3.0                    3.0
4                  2069.0            2.0                    2.0
...                   ...            ...                    ...
3802                  1.0         2030.0                 3064.0
3803                  1.0         2030.0                 3064.0
3804                  1.0         2030.0                 3064.0
3805                  1.0         2031.0                 3066.0
3806                  1.0         2032.0                 3067.0

      rank_engagements_2024  rank_posts_2024  rank_profiles_2024  year_2024
0                      10.0              3.0               232.0       2024
1                       2.0              6.0                 6.0       2024
2                       3.0             10.0                14.0       2024
3                      13.0             19.0                18.0       2024
4                       7.0             20.0                21.0       2024
...                     ...              ...                 ...        ...
3802                 2398.0            318.0               231.0       2024
3803                 2398.0            318.0               231.0       2024
3804                 2398.0            318.0               231.0       2024
3805                 2415.0            318.0               231.0       2024
3806                 2424.0            318.0               231.0       2024

[3807 rows x 24 columns]

In [47]:
# Calculate all region

all_markets = (
    brand_compare.groupby("brand_name", as_index=False)[
        ["total_emv_2023", "total_emv_2024",
         "total_impressions_2023", "total_impressions_2024",
         "total_engagements_2023", "total_engagements_2024",
         "total_posts_2023", "total_posts_2024",
         "total_profiles_2023", "total_profiles_2024"]
    ].sum()
)

all_markets["market"] = "All Markets"

brand_compare_with_all = pd.concat([brand_compare, all_markets], ignore_index=True)
print(brand_compare_with_all)

              brand_name       market  total_emv_2023  total_impressions_2023  \
0                   None         None      26348260.0            1.756907e+09
1             YSL Beauty         None      17489169.0            1.166063e+09
2          MAC Cosmetics         None      17314033.0            1.154402e+09
3                Lancome         None      13885839.0            9.258288e+08
4          Armani Beauty         None      11755431.0            7.837454e+08
...                  ...          ...             ...                     ...
3855         Urban Decay  All Markets      11918278.0            7.948106e+08
3856    Valentino Beauty  All Markets       1498006.0            9.988392e+07
3857  Versace Fragrances  All Markets         28988.0            1.934873e+06
3858          YSL Beauty  All Markets      36126569.0            2.408716e+09
3859        bareMinerals  All Markets       1453750.0            9.693670e+07

      total_engagements_2023  total_posts_2023  total_profiles_2023  \
0                 98552230.0           12371.0                  0.0
1                 36210719.0            4204.0               1549.0
2                 49218202.0            4945.0               1433.0
3                 23489841.0            3768.0               1309.0
4                 15931573.0            1819.0                841.0
...                      ...               ...                  ...
3855              41289454.0            8689.0               3519.0
3856               2614461.0             583.0                373.0
3857                 73268.0              87.0                 66.0
3858              66717346.0            9844.0               4062.0
3859               3926944.0             701.0                401.0

      rank_emv_2023  rank_impressions_2023  rank_engagements_2023  ...  \
0               1.0                    1.0                    1.0  ...
1               2.0                    2.0                    7.0  ...
2               3.0                    3.0                    2.0  ...
3               4.0                    4.0                   15.0  ...
4               5.0                    5.0                   20.0  ...
...             ...                    ...                    ...  ...
3855            NaN                    NaN                    NaN  ...
3856            NaN                    NaN                    NaN  ...
3857            NaN                    NaN                    NaN  ...
3858            NaN                    NaN                    NaN  ...
3859            NaN                    NaN                    NaN  ...

      total_impressions_2024  total_engagements_2024 total_posts_2024  \
0               1.410869e+09              70866217.0          13110.0
1               2.554223e+09             115055200.0          12871.0
2               1.580363e+09              95335298.0          10788.0
3               1.930390e+09              56035403.0           7733.0
4               2.528929e+09              73155372.0           7359.0
...                      ...                     ...              ...
3855            1.557775e+09             104718726.0          16882.0
3856            6.572302e+08              18819883.0           3990.0
3857            1.245462e+07                428357.0            205.0
3858            3.934583e+09             176055169.0          29403.0
3859            1.108376e+08               6189515.0           1760.0

      total_profiles_2024  rank_emv_2024  rank_impressions_2024  \
0                     0.0            6.0                    6.0
1                  3223.0            1.0                    1.0
2                  2466.0            4.0                    4.0
3                  2134.0            3.0                    3.0
4                  2069.0            2.0                    2.0
...                   ...            ...                    ...
3855               5095.0            NaN                    NaN
3856               2050.0            NaN                    NaN
3857                111.0            NaN                    NaN
3858               8525.0            NaN                    NaN
3859                836.0            NaN                    NaN

      rank_engagements_2024  rank_posts_2024  rank_profiles_2024  year_2024
0                      10.0              3.0               232.0       2024
1                       2.0              6.0                 6.0       2024
2                       3.0             10.0                14.0       2024
3                      13.0             19.0                18.0       2024
4                       7.0             20.0                21.0       2024
...                     ...              ...                 ...        ...
3855                    NaN              NaN                 NaN        NaN
3856                    NaN              NaN                 NaN        NaN
3857                    NaN              NaN                 NaN        NaN
3858                    NaN              NaN                 NaN        NaN
3859                    NaN              NaN                 NaN        NaN

[3860 rows x 24 columns]

2. Year over year evolution of different KPIs

In [19]:
import numpy as np

In [48]:
# Calculate YOY evolution

for metric in ["emv", "impressions", "engagements", "posts", "profiles"]:
    c2023 = f"total_{metric}_2023"
    c2024 = f"total_{metric}_2024"
    brand_compare_with_all[f"{metric}_yoy_change"] = (
        (brand_compare_with_all[c2024] - brand_compare_with_all[c2023]) /
        brand_compare_with_all[c2023].replace({0: pd.NA})
    )

brand_compare_with_all = brand_compare_with_all.sort_values(
    by="emv_yoy_change", 
    ascending=False
).reset_index(drop=True)

In [49]:
print(brand_compare_with_all)

           brand_name market  total_emv_2023  total_impressions_2023  \
0       Armani Beauty     IN            71.0                  4880.0
1           Too Faced     GR            13.0                   925.0
2       MAC Cosmetics     SG            21.0                  1458.0
3           Anastasia     TN             9.0                   666.0
4       MAC Cosmetics     IR             1.0                    84.0
...               ...    ...             ...                     ...
3855     Gucci Beauty     CV             NaN                     NaN
3856           La Mer     CV             NaN                     NaN
3857  Tom Ford Beauty     CV             NaN                     NaN
3858           Byredo     PS             NaN                     NaN
3859          Benefit     ET             NaN                     NaN

      total_engagements_2023  total_posts_2023  total_profiles_2023  \
0                      148.0               4.0                  4.0
1                       21.0               1.0                  1.0
2                       69.0               1.0                  1.0
3                       30.0               1.0                  1.0
4                        3.0               1.0                  1.0
...                      ...               ...                  ...
3855                     NaN               NaN                  NaN
3856                     NaN               NaN                  NaN
3857                     NaN               NaN                  NaN
3858                     NaN               NaN                  NaN
3859                     NaN               NaN                  NaN

      rank_emv_2023  rank_impressions_2023  rank_engagements_2023  ...  \
0            1466.0                 1897.0                 1748.0  ...
1            1524.0                 2273.0                 1870.0  ...
2            1516.0                 2182.0                 1822.0  ...
3            1528.0                 2333.0                 1861.0  ...
4            1536.0                 2434.0                 1888.0  ...
...             ...                    ...                    ...  ...
3855            NaN                    NaN                    NaN  ...
3856            NaN                    NaN                    NaN  ...
3857            NaN                    NaN                    NaN  ...
3858            NaN                    NaN                    NaN  ...
3859            NaN                    NaN                    NaN  ...

      rank_impressions_2024  rank_engagements_2024 rank_posts_2024  \
0                     141.0                  172.0           235.0
1                     355.0                  238.0           312.0
2                     298.0                  245.0           309.0
3                     554.0                  585.0           310.0
4                    1148.0                 1149.0           310.0
...                     ...                    ...             ...
3855                 3064.0                 2398.0           318.0
3856                 3064.0                 2398.0           318.0
3857                 3064.0                 2398.0           318.0
3858                 3066.0                 2415.0           318.0
3859                 3067.0                 2424.0           318.0

      rank_profiles_2024  year_2024  emv_yoy_change  impressions_yoy_change  \
0                  199.0       2024     7607.408451             7379.225615
1                  227.0       2024     6171.307692             5782.247568
2                  228.0       2024     5738.904762             5510.694102
3                  229.0       2024     2709.444444             2441.183183
4                  228.0       2024     2693.000000             2139.666667
...                  ...        ...             ...                     ...
3855               231.0       2024             NaN                     NaN
3856               231.0       2024             NaN                     NaN
3857               231.0       2024             NaN                     NaN
3858               231.0       2024             NaN                     NaN
3859               231.0       2024             NaN                     NaN

      engagements_yoy_change  posts_yoy_change  profiles_yoy_change
0                8261.743243             20.25                 7.25
1               24925.142857              6.00                  4.0
2                7253.666667              9.00                  3.0
3                2608.200000              8.00                  2.0
4                2822.333333              8.00                  3.0
...                      ...               ...                  ...
3855                     NaN               NaN                  NaN
3856                     NaN               NaN                  NaN
3857                     NaN               NaN                  NaN
3858                     NaN               NaN                  NaN
3859                     NaN               NaN                  NaN

[3860 rows x 29 columns]

In [51]:
ami_rows = brand_compare_with_all[brand_compare_with_all["brand_name"] == "Armani Beauty"]
ami_rows.head(10)

,brand_name,market,total_emv_2023,total_impressions_2023,total_engagements_2023,total_posts_2023,total_profiles_2023,rank_emv_2023,rank_impressions_2023,rank_engagements_2023,...,rank_impressions_2024,rank_engagements_2024,rank_posts_2024,rank_profiles_2024,year_2024,emv_yoy_change,impressions_yoy_change,engagements_yoy_change,posts_yoy_change,profiles_yoy_change
0,Armani Beauty,IN,71.0,4880.0,148.0,4.0,4.0,1466.0,1897.0,1748.0,...,141.0,172.0,235.0,199.0,2024,7607.408451,7379.225615,8261.743243,20.250000,7.25
36,Armani Beauty,SR,41.0,2761.0,173.0,1.0,1.0,1496.0,2043.0,1727.0,...,557.0,1687.0,315.0,231.0,2024,586.000000,580.160811,8.289017,3.000000,0.0
97,Armani Beauty,PR,538.0,36062.0,980.0,5.0,3.0,1147.0,1221.0,1330.0,...,323.0,643.0,289.0,221.0,2024,187.622677,186.630082,59.472449,5.000000,2.666667
105,Armani Beauty,HN,80.0,5426.0,330.0,2.0,2.0,1458.0,1864.0,1610.0,...,700.0,523.0,308.0,229.0,2024,162.212500,159.472171,299.615152,4.500000,0.5
109,Armani Beauty,CA,218.0,14671.0,1066.0,6.0,4.0,1333.0,1527.0,1302.0,...,478.0,396.0,283.0,217.0,2024,158.903670,157.474542,184.212946,5.000000,2.75
121,Armani Beauty,PH,11.0,797.0,29.0,1.0,1.0,1526.0,2300.0,1862.0,...,1339.0,1310.0,278.0,221.0,2024,135.272727,125.962359,182.103448,40.000000,10.0
145,Armani Beauty,TR,40.0,2715.0,140.0,2.0,2.0,1497.0,2050.0,1755.0,...,988.0,979.0,292.0,224.0,2024,109.400000,107.709392,105.900000,12.500000,3.0
149,Armani Beauty,CO,38.0,2564.0,92.0,1.0,1.0,1499.0,2066.0,1800.0,...,1015.0,843.0,298.0,223.0,2024,105.315789,104.271841,263.706522,20.000000,8.0
165,Armani Beauty,MY,1058.0,70666.0,1688.0,7.0,6.0,978.0,1005.0,1176.0,...,331.0,837.0,317.0,231.0,2024,89.249527,89.080208,14.040877,-0.714286,-0.833333
178,Armani Beauty,NG,1616.0,107985.0,7944.0,6.0,5.0,868.0,876.0,772.0,...,287.0,306.0,285.0,220.0,2024,79.914604,79.733741,43.270015,4.666667,1.4

3. Market share of Posts, Profiles and Impressions

In [52]:
# Calculate market share in 2023 & 2024

metrics = ["posts", "profiles", "impressions"]

for metric in metrics:
    # 2023
    total_2023 = brand_compare_with_all.groupby("market")[f"total_{metric}_2023"].transform("sum")
    brand_compare_with_all[f"{metric}_market_share_2023"] = (
        brand_compare_with_all[f"total_{metric}_2023"] / total_2023 * 100
    )
    
    # 2024
    total_2024 = brand_compare_with_all.groupby("market")[f"total_{metric}_2024"].transform("sum")
    brand_compare_with_all[f"{metric}_market_share_2024"] = (
        brand_compare_with_all[f"total_{metric}_2024"] / total_2024 * 100
    )

In [ ]:
# Calculate market share in 2023 & 2024

metrics = ["emv", "impressions", "engagements", "posts", "profiles"]

for metric in metrics:

    total_2023 = brand_compare_with_all.groupby("market")[f"total_{metric}_2023"].transform("sum")
    brand_compare_with_all[f"{metric}_market_share_2023"] = (
        brand_compare_with_all[f"total_{metric}_2023"] / total_2023 * 100
    )
    total_2024 = brand_compare_with_all.groupby("market")[f"total_{metric}_2024"].transform("sum")
    brand_compare_with_all[f"{metric}_market_share_2024"] = (
        brand_compare_with_all[f"total_{metric}_2024"] / total_2024 * 100
    )


for metric in metrics:
    mask = brand_compare_with_all["market"] == "All Markets"
    total_2023_all = brand_compare_with_all.loc[mask, f"total_{metric}_2023"].sum()
    total_2024_all = brand_compare_with_all.loc[mask, f"total_{metric}_2024"].sum()
    brand_compare_with_all.loc[mask, f"{metric}_market_share_2023"] = (
        brand_compare_with_all.loc[mask, f"total_{metric}_2023"] / total_2023_all * 100
    )
    brand_compare_with_all.loc[mask, f"{metric}_market_share_2024"] = (
        brand_compare_with_all.loc[mask, f"total_{metric}_2024"] / total_2024_all * 100
    )

In [85]:
# Calculate YOY evolution of market share

for metric in metrics:
    c2023 = f"{metric}_market_share_2023"
    c2024 = f"{metric}_market_share_2024"
    brand_compare_with_all[f"{metric}_market_share_change"] = (
        (brand_compare_with_all[c2024] - brand_compare_with_all[c2023]) /
        brand_compare_with_all[c2023].replace({0: pd.NA}) 
    )

brand_compare_with_all.head(10)

,brand_name,market,total_emv_2023,total_impressions_2023,total_engagements_2023,total_posts_2023,total_profiles_2023,rank_emv_2023,rank_impressions_2023,rank_engagements_2023,...,impressions_market_share_2024,posts_market_share_change,profiles_market_share_change,impressions_market_share_change,emv_market_share_2023,emv_market_share_2024,engagements_market_share_2023,engagements_market_share_2024,emv_market_share_change,engagements_market_share_change
0,Armani Beauty,IN,71.0,4880.0,148.0,4.0,4.0,1466.0,1897.0,1748.0,...,5.818310,3.616213,1.252497,445.742933,0.012637,5.818495,0.006683,3.610818,459.436367,539.301358
1,Too Faced,GR,13.0,925.0,21.0,1.0,1.0,1524.0,2273.0,1870.0,...,8.450231,1.445783,1.647059,1050.206146,0.007533,8.450808,0.005334,13.890189,1120.792765,2602.901158
2,MAC Cosmetics,SG,21.0,1458.0,69.0,1.0,1.0,1516.0,2182.0,1822.0,...,34.104033,7.876404,2.022222,2179.644870,0.015021,34.106163,0.026581,37.240535,2269.560934,1400.042891
3,Anastasia,TN,9.0,666.0,30.0,1.0,1.0,1528.0,2333.0,1861.0,...,37.902313,14.130435,4.205882,1790.304859,0.019082,37.915384,0.021474,41.366627,1985.976782,1925.374876
4,MAC Cosmetics,IR,1.0,84.0,3.0,1.0,1.0,1536.0,2434.0,1888.0,...,7.342315,-0.197183,-0.228070,131.739432,0.044072,7.353222,0.046780,8.652127,165.844611,183.953641
5,Bobbi Brown,NG,8.0,580.0,15.0,1.0,1.0,1529.0,2354.0,1876.0,...,0.791060,6.624021,2.470085,301.597277,0.002405,0.790932,0.000760,0.828143,327.840014,1088.168612
6,Dior Beauty,EG,20.0,1385.0,119.0,1.0,1.0,1517.0,2194.0,1775.0,...,9.611705,2.111111,2.207921,207.518054,0.044401,9.612777,0.066467,8.609077,215.498958,128.523919
7,The Ordinary,PS,28.0,1929.0,75.0,1.0,1.0,1509.0,2119.0,1816.0,...,40.922774,10.658363,1.153846,2905.900596,0.013627,40.946776,0.004581,24.357185,3003.762134,5315.787073
8,The Ordinary,JP,51.0,3487.0,421.0,3.0,3.0,1486.0,1979.0,1553.0,...,2.348103,3.927989,3.233766,1819.607175,0.001258,2.348133,0.006373,0.767164,1866.082116,119.383915
9,Kylie Cosmetics,ZA,71.0,4804.0,204.0,2.0,2.0,1466.0,1902.0,1700.0,...,2.915843,7.521567,4.796225,562.065678,0.005103,2.915989,0.010223,7.426932,570.394971,725.499228

In [54]:
print(brand_compare_with_all)

           brand_name market  total_emv_2023  total_impressions_2023  \
0       Armani Beauty     IN            71.0                  4880.0
1           Too Faced     GR            13.0                   925.0
2       MAC Cosmetics     SG            21.0                  1458.0
3           Anastasia     TN             9.0                   666.0
4       MAC Cosmetics     IR             1.0                    84.0
...               ...    ...             ...                     ...
3855     Gucci Beauty     CV             NaN                     NaN
3856           La Mer     CV             NaN                     NaN
3857  Tom Ford Beauty     CV             NaN                     NaN
3858           Byredo     PS             NaN                     NaN
3859          Benefit     ET             NaN                     NaN

      total_engagements_2023  total_posts_2023  total_profiles_2023  \
0                      148.0               4.0                  4.0
1                       21.0               1.0                  1.0
2                       69.0               1.0                  1.0
3                       30.0               1.0                  1.0
4                        3.0               1.0                  1.0
...                      ...               ...                  ...
3855                     NaN               NaN                  NaN
3856                     NaN               NaN                  NaN
3857                     NaN               NaN                  NaN
3858                     NaN               NaN                  NaN
3859                     NaN               NaN                  NaN

      rank_emv_2023  rank_impressions_2023  rank_engagements_2023  ...  \
0            1466.0                 1897.0                 1748.0  ...
1            1524.0                 2273.0                 1870.0  ...
2            1516.0                 2182.0                 1822.0  ...
3            1528.0                 2333.0                 1861.0  ...
4            1536.0                 2434.0                 1888.0  ...
...             ...                    ...                    ...  ...
3855            NaN                    NaN                    NaN  ...
3856            NaN                    NaN                    NaN  ...
3857            NaN                    NaN                    NaN  ...
3858            NaN                    NaN                    NaN  ...
3859            NaN                    NaN                    NaN  ...

      profiles_yoy_change  posts_market_share_2023 posts_market_share_2024  \
0                    7.25                 0.835073                3.854875
1                     4.0                 1.149425                2.811245
2                     3.0                 1.265823               11.235955
3                     2.0                 0.862069               13.043478
4                     3.0                 5.263158                4.225352
...                   ...                      ...                     ...
3855                  NaN                      NaN                6.666667
3856                  NaN                      NaN                6.666667
3857                  NaN                      NaN                6.666667
3858                  NaN                      NaN                0.355872
3859                  NaN                      NaN                0.909091

      profiles_market_share_2023  profiles_market_share_2024  \
0                       1.626016                    3.662597
1                       1.851852                    4.901961
2                       2.941176                    8.888889
3                       1.694915                    8.823529
4                       9.090909                    7.017544
...                          ...                         ...
3855                         NaN                    7.692308
3856                         NaN                    7.692308
3857                         NaN                    7.692308
3858                         NaN                    0.641026
3859                         NaN                    1.724138

      impressions_market_share_2023  impressions_market_share_2024  \
0                          0.013024                       5.818310
1                          0.008039                       8.450231
2                          0.015639                      34.104033
3                          0.021159                      37.902313
4                          0.055314                       7.342315
...                             ...                            ...
3855                            NaN                       0.200024
3856                            NaN                       0.200024
3857                            NaN                       0.200024
3858                            NaN                       0.001214
3859                            NaN                       0.000000

      posts_market_share_change  profiles_market_share_change  \
0                      3.616213                      1.252497
1                      1.445783                      1.647059
2                      7.876404                      2.022222
3                     14.130435                      4.205882
4                     -0.197183                     -0.228070
...                         ...                           ...
3855                        NaN                           NaN
3856                        NaN                           NaN
3857                        NaN                           NaN
3858                        NaN                           NaN
3859                        NaN                           NaN

      impressions_market_share_change
0                          445.742933
1                         1050.206146
2                         2179.644870
3                         1790.304859
4                          131.739432
...                               ...
3855                              NaN
3856                              NaN
3857                              NaN
3858                              NaN
3859                              NaN

[3860 rows x 38 columns]

In [55]:
all_markets_rows = brand_compare_with_all[brand_compare_with_all["market"] == "All Markets"]
print(all_markets_rows[["brand_name", "posts_market_share_change"]])

                      brand_name  posts_market_share_change
494            Helena Rubinstein                  -0.488077
667         Dolce Gabbana Beauty                  -0.306073
682             Valentino Beauty                   1.473097
686           Versace Fragrances                  -0.148526
732                   Shu Uemura                  -0.298656
782              Givenchy Beauty                   0.292056
837            Rabanne Fragrance                   0.144144
849                 Prada beauty                   1.872865
852                Laura Mercier                   0.027705
860   Carolina Herrera Fragrance                  -0.090377
875                     Shiseido                   0.269927
889                    Anastasia                   0.580289
943                  Cle de Peau                  -0.114290
969              Tarte Cosmetics                   0.747145
988                     Clinique                  -0.067578
1008           Charlotte Tilbury                   0.087668
1045               Chanel Beauty                  -0.219910
1049                     Clarins                   0.002209
1051                    Guerlain                  -0.017028
1080                        NARS                  -0.072609
1091               Armani Beauty                   0.245127
1123                 Urban Decay                  -0.297913
1126                     Benefit                   0.355920
1162                   Too Faced                   0.070710
1166                 Dior Beauty                  -0.194747
1181             Tom Ford Beauty                  -0.269156
1191                      Byredo                  -0.426041
1200                  YSL Beauty                   0.079336
1202                Sisley Paris                  -0.590157
1223         Burberry Fragrances                   0.089133
1249                       Fresh                   0.216429
1251    Dolce Gabbana Fragrances                  -0.556562
1254                    Diptyque                  -0.368874
1260                The Ordinary                  -0.003539
1262                  La Prairie                  -0.416269
1269                Estée Lauder                  -0.281283
1287                     Lancome                  -0.266690
1290                      La Mer                  -0.307238
1296                     Origins                   0.196058
1298                     Kiehl's                  -0.073839
1300                 Bobbi Brown                  -0.327529
1309               MAC Cosmetics                  -0.232825
1318                   Sulwhasoo                  -0.342842
1356                   Jo Malone                  -0.582548
1365                bareMinerals                  -0.092741
1378                Gucci Beauty                  -0.289525
1383           Mugler Fragrances                  -0.261483
1386             Kylie Cosmetics                  -0.250115
1419               Kenzo Parfums                  -0.385693
1454  Maison Margiela Fragrances                   0.070613
1464                    Biotherm                  -0.538059
1588               Hermes Beauty                  -0.587020
1881                       SK-II                  -0.057770

Push table to Bigquery & Firebase

In [58]:
from google.cloud import bigquery
from google.oauth2 import service_account
import pyarrow
import tempfile
import shutil

In [95]:
# Push

tmp_path = os.path.join(tempfile.gettempdir(), "brand_compare_KPI.csv")
brand_compare_with_all.to_csv(tmp_path, index=False, encoding="utf-8")

job = client.load_table_from_file(
    open(tmp_path, "rb"),
    table_ref,
    job_config=bigquery.LoadJobConfig(
        write_disposition="WRITE_TRUNCATE",
        source_format=bigquery.SourceFormat.CSV,
        skip_leading_rows=1,
        autodetect=True
    )
)

job.result()

LoadJob<project=benchmarkcasestudy, location=US, id=c2d82abc-9104-4de5-bf58-2071e42d84e7>

In [72]:
import firebase_admin
from firebase_admin import credentials, firestore

In [63]:
db = firestore.client()
collection_name = "brand_compare_KPI"

In [64]:
# Accelerate

batch = db.batch()
batch_size = 500 
counter = 0

4. Post Monthly Evolution

In [27]:
# Define function to calculate post monthly evolution

def post_monthly_evolution(year):
    query = f"""
    SELECT
        J.Timestamp AS date,
        I.Brand_name AS brand_name,
        J.Emv AS emv,
        J.Impressions AS impressions,
        J."Eng._Rate" AS engagement_rate,
        J.Followers AS followers,
        J.Post_id AS posts
    FROM "{year}_LOT_J" AS J
    LEFT JOIN "{year}_LOT_H" AS H ON J.Post_id = H.Post_id
    LEFT JOIN "{year}_LOT_I" AS I ON H.Brand_id = I.Brand_id
    WHERE J."Timestamp" IS NOT NULL
    """
    
    df = pd.read_sql(query, conn)

    # Convert date format and extract month

    df["date"] = pd.to_datetime(df["date"], errors="coerce", infer_datetime_format=True)
    df["month"] = df["date"].dt.to_period("M").astype(str)

    # Calculate engagement 
    
    if "engagement_rate" in df.columns:
        df["engagements"] = df["followers"] * df["engagement_rate"]
    else:
        df["engagements"] = None

    # Group by brand name

    monthly = df.groupby(["month", "brand_name"], as_index=False).agg(
        total_posts=("posts", "nunique"),
        total_impressions=("impressions", "sum"),
        total_engagements=("engagements", "sum"),
        total_emv=("emv", "sum")
    )

    monthly["year"] = year

    return monthly

In [28]:
monthly_2023 = post_monthly_evolution("2023")

C:\Users\z\AppData\Local\Temp\ipykernel_2784\615885820.py:23: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df["date"] = pd.to_datetime(df["date"], errors="coerce", infer_datetime_format=True)

In [29]:
print(monthly_2023)

       month          brand_name  total_posts  total_impressions  \
0    2023-01           Anastasia          694         45647171.0
1    2023-01       Armani Beauty          138        128725841.0
2    2023-01             Benefit          451        139708366.0
3    2023-01            Biotherm            5           159504.0
4    2023-01         Bobbi Brown          160         30874235.0
..       ...                 ...          ...                ...
625  2023-12         Urban Decay          650         84457487.0
626  2023-12    Valentino Beauty           98          7599674.0
627  2023-12  Versace Fragrances           13           134100.0
628  2023-12          YSL Beauty         1356        151150536.0
629  2023-12        bareMinerals           51          4994397.0

     total_engagements  total_emv  year
0         2.565914e+06   684408.0  2023
1         1.309523e+06  1930840.0  2023
2         3.562579e+06  2095452.0  2023
3         7.314000e+03     2391.0  2023
4         1.505953e+06   463045.0  2023
..                 ...        ...   ...
625       2.818662e+06  1266570.0  2023
626       4.175010e+05   113952.0  2023
627       2.065000e+03     2006.0  2023
628       5.990334e+06  2266655.0  2023
629       1.949430e+05    74892.0  2023

[630 rows x 7 columns]

In [30]:
monthly_2024 = post_monthly_evolution("2024")

post_monthly = pd.concat([monthly_2023, monthly_2024]).reset_index(drop=True)
print(post_monthly)

C:\Users\z\AppData\Local\Temp\ipykernel_2784\615885820.py:23: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df["date"] = pd.to_datetime(df["date"], errors="coerce", infer_datetime_format=True)

        month          brand_name  total_posts  total_impressions  \
0     2023-01           Anastasia          694         45647171.0
1     2023-01       Armani Beauty          138        128725841.0
2     2023-01             Benefit          451        139708366.0
3     2023-01            Biotherm            5           159504.0
4     2023-01         Bobbi Brown          160         30874235.0
...       ...                 ...          ...                ...
1254  2024-12         Urban Decay         1320        165686214.0
1255  2024-12    Valentino Beauty          657         76232993.0
1256  2024-12  Versace Fragrances            8            98200.0
1257  2024-12          YSL Beauty         2649        273110760.0
1258  2024-12        bareMinerals          184         18575364.0

      total_engagements  total_emv  year
0          2.565914e+06   684408.0  2023
1          1.309523e+06  1930840.0  2023
2          3.562579e+06  2095452.0  2023
3          7.314000e+03     2391.0  2023
4          1.505953e+06   463045.0  2023
...                 ...        ...   ...
1254       1.493234e+07  2484700.0  2024
1255       2.976320e+06  1143209.0  2024
1256       4.231000e+03     1470.0  2024
1257       1.220134e+07  4095494.0  2024
1258       1.598484e+06   278552.0  2024

[1259 rows x 7 columns]

5. Ranking Post by Profile Category

In [32]:
# Define function to rank post by profile category

def ranking_post_by_category(year):
    query = f"""
    SELECT 
        E."Profile_label_-_category" AS profile_category,
        COUNT(DISTINCT J.Post_id) AS total_posts,
        SUM(J.Impressions) AS total_impressions,
        SUM(J.Emv) AS total_emv,
        SUM(J.Likes + J.Comments + J.Shares) AS total_engagements
    FROM "{year}_LOT_J" AS J
    LEFT JOIN (
        SELECT DISTINCT Account_id, Post_id
        FROM "{year}_LOT_A"
    ) AS A ON J.Post_id = A.Post_id
    INNER JOIN "{year}_LOT_C" AS C ON A.Account_id = C.Account_id
    LEFT JOIN "{year}_LOT_E" AS E ON C.Ally_id = E.Ally_id
    WHERE E."Profile_label_-_category" IS NOT NULL
    GROUP BY E."Profile_label_-_category"
    ORDER BY total_posts DESC;
    """

    df = pd.read_sql(query, conn)
    df["year"] = year
    return df

In [22]:
pd.read_sql('PRAGMA table_info("2023_LOT_E");', conn)

   cid                          name  type  notnull dflt_value  pk
0    0                       Ally_id  TEXT        0       None   0
1    1                      Username  TEXT        0       None   0
2    2      Profile_label_-_category  TEXT        0       None   0
3    3  Profile_label_-_sub-category  TEXT        0       None   0
4    4                          Code  TEXT        0       None   0

In [34]:
rank_profile_2023 = ranking_post_by_category("2023")
rank_profile_2024 = ranking_post_by_category("2024")

# Merge two years

rank_profile_compare = rank_profile_2023.merge(
    rank_profile_2024, 
    on="profile_category", 
    suffixes=("_2023", "_2024"),
    how="outer"
)


print(rank_profile_compare)

  profile_category  total_posts_2023  total_impressions_2023  total_emv_2023  \
0  Digital Creator             79848            1.316793e+10     197484469.0
1    Beauty Expert             31117            4.145768e+09      62173131.0
2           Others              8669            1.035951e+09      15535427.0
3        Celebrity              6427            2.636047e+09      39538155.0
4              KOL              3301            8.234935e+08      12351065.0
5         Business              2409            3.035719e+08       4552527.0
6            Media               963            1.661223e+08       2491423.0

   total_engagements_2023 year_2023  total_posts_2024  total_impressions_2024  \
0             552079928.0      2023            206341            2.171086e+10
1             179329528.0      2023             61509            6.025056e+09
2              32197483.0      2023             13906            1.476309e+09
3              80146342.0      2023             11923            3.032433e+09
4              22496564.0      2023              6738            1.094780e+09
5               8403070.0      2023              4244            5.448121e+08
6               4678189.0      2023              1451            1.977706e+08

   total_emv_2024  total_engagements_2024 year_2024
0     325569803.0             979922589.0      2024
1      90348235.0             265251755.0      2024
2      22138428.0              52342821.0      2024
3      45481443.0              82630299.0      2024
4      16418770.0              33824273.0      2024
5       8170260.0               7982805.0      2024
6       2965939.0               7277045.0      2024

In [35]:
# Calculate YOY

for metric in ["total_posts", "total_impressions", "total_emv", "total_engagements"]:
    rank_profile_compare[f"{metric}_yoy_change"] = (
        (rank_profile_compare[f"{metric}_2024"] - rank_profile_compare[f"{metric}_2023"])
        / rank_profile_compare[f"{metric}_2023"]
    )

print(rank_profile_compare)

  profile_category  total_posts_2023  total_impressions_2023  total_emv_2023  \
0  Digital Creator             79848            1.316793e+10     197484469.0
1    Beauty Expert             31117            4.145768e+09      62173131.0
2           Others              8669            1.035951e+09      15535427.0
3        Celebrity              6427            2.636047e+09      39538155.0
4              KOL              3301            8.234935e+08      12351065.0
5         Business              2409            3.035719e+08       4552527.0
6            Media               963            1.661223e+08       2491423.0

   total_engagements_2023 year_2023  total_posts_2024  total_impressions_2024  \
0             552079928.0      2023            206341            2.171086e+10
1             179329528.0      2023             61509            6.025056e+09
2              32197483.0      2023             13906            1.476309e+09
3              80146342.0      2023             11923            3.032433e+09
4              22496564.0      2023              6738            1.094780e+09
5               8403070.0      2023              4244            5.448121e+08
6               4678189.0      2023              1451            1.977706e+08

   total_emv_2024  total_engagements_2024 year_2024  total_posts_yoy_change  \
0     325569803.0             979922589.0      2024                1.584172
1      90348235.0             265251755.0      2024                0.976701
2      22138428.0              52342821.0      2024                0.604107
3      45481443.0              82630299.0      2024                0.855142
4      16418770.0              33824273.0      2024                1.041200
5       8170260.0               7982805.0      2024                0.761727
6       2965939.0               7277045.0      2024                0.506750

   total_impressions_yoy_change  total_emv_yoy_change  \
0                      0.648768              0.648584
1                      0.453303              0.453172
2                      0.425077              0.425029
3                      0.150371              0.150318
4                      0.329434              0.329340
5                      0.794672              0.794665
6                      0.190512              0.190460

   total_engagements_yoy_change
0                      0.774965
1                      0.479130
2                      0.625681
3                      0.030993
4                      0.503531
5                     -0.050013
6                      0.555526

6.  Ranking most impactful profiles per brand

In [96]:

def impactful_profiles_2024(top_n_brands=4):
    #  Find out most visible brands（order by impressions）

    top_brands_query = """
        SELECT 
            I.Brand_name,
            SUM(J.Impressions) AS total_impressions
        FROM "2024_LOT_J" AS J
        INNER JOIN "2024_LOT_H" AS H ON J.Post_id = H.Post_id
        LEFT JOIN "2024_LOT_I" AS I ON H.Brand_id = I.Brand_id
        GROUP BY I.Brand_name
        ORDER BY total_impressions DESC
        LIMIT ?;
    """
    top_brands = pd.read_sql(top_brands_query, conn, params=(top_n_brands,))
    brand_list = tuple(top_brands["Brand_name"].tolist())

    # Split tier

    conn.execute("DROP TABLE IF EXISTS tmp_2024_tier;")
    tier_sql = """
        CREATE TEMP TABLE tmp_2024_tier AS
        SELECT 
            C.Ally_id,
            MAX(B.Followers) AS max_followers,
            CASE
                WHEN MAX(B.Followers) >= 1000000 THEN 'Mega'
                WHEN MAX(B.Followers) >= 500000 THEN 'Macro'
                WHEN MAX(B.Followers) >= 100000 THEN 'Midtier'
                WHEN MAX(B.Followers) >= 10000 THEN 'Micro'
                ELSE 'Nano'
            END AS ally_tier
        FROM "2024_LOT_B" AS B
        LEFT JOIN "2024_LOT_C" AS C ON B.Account_id = C.Account_id
        GROUP BY C.Ally_id;
    """
    conn.execute(tier_sql)
    conn.commit()


    # Profile performance

    main_query = f"""
        SELECT 
            I.Brand_name AS brand_name,
            D.Geo_code AS market,
            C.Ally_id,
            E."Profile_label_-_category" AS ally_category,
            T.ally_tier,
            STRFTIME('%Y-%m', J.Timestamp) AS month,
            SUM(J.Impressions) AS total_impressions,
            SUM(J.Emv) AS total_emv,
            SUM(J.Likes + J.Comments + J.Shares) AS total_engagements,
            MAX(T.max_followers) AS followers,
            COUNT(DISTINCT J.Post_id) AS total_posts
        FROM "2024_LOT_J" AS J
        LEFT JOIN "2024_LOT_H" AS H ON J.Post_id = H.Post_id
        LEFT JOIN "2024_LOT_I" AS I ON H.Brand_id = I.Brand_id
        LEFT JOIN "2024_LOT_A" AS A ON J.Post_id = A.Post_id
        LEFT JOIN "2024_LOT_C" AS C ON A.Account_id = C.Account_id
        LEFT JOIN "2024_LOT_D" AS D ON C.Ally_id = D.Ally_id
        LEFT JOIN "2024_LOT_E" AS E ON C.Ally_id = E.Ally_id
        LEFT JOIN tmp_2024_tier AS T ON C.Ally_id = T.Ally_id
        WHERE I.Brand_name IN {brand_list}
        GROUP BY 
           month,I.Brand_name, D.Geo_code,
           C.Ally_id, E."Profile_label_-_category", ally_tier
        ORDER BY total_emv DESC;
    """

    df = pd.read_sql(main_query, conn)
    df["year"] = 2024

    all_markets = (
        df.groupby(
            ["brand_name", "Ally_id", "ally_category", "ally_tier", "month"],
            as_index=False
        )[["total_impressions", "total_emv", "total_engagements", "followers", "total_posts"]]
        .sum()
    )
    all_markets["market"] = "All Markets"

    df_with_all = pd.concat([df, all_markets], ignore_index=True)

    return df_with_all

In [97]:
impactful_2024 = impactful_profiles_2024(top_n_brands=4)
print(impactful_2024)

           brand_name       market                      Ally_id  \
0       Armani Beauty         None                  ig:43678222
1             Lancome           MX       tk:6788899448527504389
2          YSL Beauty         None                 ig:304358009
3          YSL Beauty         None               ig:56105303581
4       Armani Beauty         None               ig:49734649834
...               ...          ...                          ...
122894     YSL Beauty  All Markets  yt:UCxbo-dmcf8PX1uhPLU76YhA
122895     YSL Beauty  All Markets  yt:UCxbo-dmcf8PX1uhPLU76YhA
122896     YSL Beauty  All Markets  yt:UCxbo-dmcf8PX1uhPLU76YhA
122897     YSL Beauty  All Markets  yt:UCxbo-dmcf8PX1uhPLU76YhA
122898     YSL Beauty  All Markets  yt:UCyujzJvIm9hSBi6qiyT18BQ

          ally_category ally_tier    month  total_impressions  total_emv  \
0             Celebrity      Mega  2024-11        124400000.0  1866000.0
1       Digital Creator     Macro  2024-09         70600000.0  1059000.0
2       Digital Creator      Mega  2024-11         43100000.0   646499.0
3       Digital Creator      Mega  2024-04         34557316.0   518359.0
4       Digital Creator   Midtier  2024-05         32827900.0   492418.0
...                 ...       ...      ...                ...        ...
122894  Digital Creator     Micro  2024-08             1997.0       29.0
122895  Digital Creator     Micro  2024-10             6258.0       91.0
122896  Digital Creator     Micro  2024-11             1450.0       21.0
122897  Digital Creator     Micro  2024-12             1215.0       17.0
122898  Digital Creator     Micro  2024-10             9462.0      141.0

        total_engagements   followers  total_posts    year
0                107383.0   2623608.0            1  2024.0
1                299762.0    701100.0            1  2024.0
2                595773.0  88500000.0            1  2024.0
3               4153293.0   1061890.0            3  2024.0
4                712521.0    263863.0            4  2024.0
...                   ...         ...          ...     ...
122894              517.0     49700.0            2     NaN
122895             1293.0     49700.0            7     NaN
122896              345.0     49700.0            2     NaN
122897              186.0     49700.0            2     NaN
122898              468.0     64900.0            1     NaN

[122899 rows x 12 columns]